### ISSUE TITLE
Can not unzip.

### ISSUE THREAD

**Issue by HuaianWu** [nanqinlang/shadowsocksr#1]
Can not unzip on MacOS.😆

**Comment by nanqinlang** [comment]
@HuaianWu  
是哪个文件不能解压呢 我就是用的很普通的zip压缩啊

**Comment by HuaianWu** [comment]
Each zip file can not unzip on MacOS by Mac default zip tool. I have already done this on Windows.
Really Thx for backup these repo.Orz

**Comment by nanqinlang** [comment]
@HuaianWu  
em...i'm sorry to hear that cause i know little about MacOS  
you're welcome.
